# Copyright (c) 2026 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 11:43:31.376764
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('client_id', sa.String(length=200), nullable=False),
    sa.Column('client_secret_enc', sa.Text(), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('etd_tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stats_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('convictions_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('convictions_watermark', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('convicted_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('etd_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('original_verdict', sa.String(length=32), nullable=True),
    sa.Column('is_retro_verdict', sa.Boolean(), nullable=False),
    sa.Column('verdict_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_risk', sa.String(length=80), nullable=True),
    sa.Column('techniques', sa.JSON(), nullable=True),
    sa.Column('rule_type', sa.String(length=32), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('envelope_from', sa.String(length=320), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=True),
    sa.Column('mailboxes', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('urls', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('secure_email_gateway', sa.String(length=80), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('action_folder', sa.String(length=32), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_auto_remediated', sa.Boolean(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'etd_id', name='uq_convicted_tenant_etd_id')
    )
    with op.batch_alter_table('convicted_messages', schema=None) as batch_op:
        batch_op.create_index('ix_convicted_tenant_dir', ['tenant_id', 'direction'], unique=False)
        batch_op.create_index('ix_convicted_tenant_ts', ['tenant_id', 'timestamp'], unique=False)

    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('incoming', sa.Integer(), nullable=False),
    sa.Column('outgoing', sa.Integer(), nullable=False),
    sa.Column('internal', sa.Integer(), nullable=False),
    sa.Column('malicious', sa.Integer(), nullable=False),
    sa.Column('phishing', sa.Integer(), nullable=False),
    sa.Column('bec', sa.Integer(), nullable=False),
    sa.Column('scam', sa.Integer(), nullable=False),
    sa.Column('spam', sa.Integer(), nullable=False),
    sa.Column('graymail', sa.Integer(), nullable=False),
    sa.Column('retro_verdicts', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'day', name='uq_daily_stats_tenant_day')
    )
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_stats_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('report_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('report_key', sa.String(length=60), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('output_format', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_schedules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('top_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('malicious', sa.Integer(), nullable=False),
    sa.Column('phishing', sa.Integer(), nullable=False),
    sa.Column('bec', sa.Integer(), nullable=False),
    sa.Column('scam', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('top_entries', schema=None) as batch_op:
        batch_op.create_index('ix_top_entries_lookup', ['tenant_id', 'kind', 'period_end'], unique=False)

    op.create_table('report_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('report_key', sa.String(length=60), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('html_path', sa.String(length=400), nullable=True),
    sa.Column('pdf_path', sa.String(length=400), nullable=True),
    sa.Column('delivered_to', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['report_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_runs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_runs_tenant_id'))

    op.drop_table('report_runs')
    with op.batch_alter_table('top_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_top_entries_lookup')

    op.drop_table('top_entries')
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_schedules_tenant_id'))

    op.drop_table('report_schedules')
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_stats_tenant_id'))

    op.drop_table('daily_stats')
    with op.batch_alter_table('convicted_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_convicted_tenant_ts')
        batch_op.drop_index('ix_convicted_tenant_dir')

    op.drop_table('convicted_messages')
    op.drop_table('tenants')
    op.drop_table('settings')
    # ### end Alembic commands ###
