# Copyright (c) 2026 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
"""history backfill and api quota bookkeeping

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-22 22:09:58.411733
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backfill_cursor', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('backfill_done_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('stats_backfilled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('api_calls_day', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('api_calls_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('api_calls_count')
        batch_op.drop_column('api_calls_day')
        batch_op.drop_column('stats_backfilled')
        batch_op.drop_column('backfill_done_at')
        batch_op.drop_column('backfill_cursor')

    # ### end Alembic commands ###
