# Copyright (c) 2026 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
"""Log Export (audit trail, verdict changes, sender-domain history), DNS cache and tenant reporting profile

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-23
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_cache',
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('domain', 'kind')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_hash', name='uq_audit_events_tenant_hash')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_tenant_ts', ['tenant_id', 'timestamp'], unique=False)

    op.create_table('log_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=20), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('path_hash', sa.String(length=64), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('log_hour', sa.Integer(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'path_hash', name='uq_log_files_tenant_path')
    )
    with op.batch_alter_table('log_files', schema=None) as batch_op:
        batch_op.create_index('ix_log_files_tenant_type_date', ['tenant_id', 'log_type', 'log_date'], unique=False)

    op.create_table('message_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('internet_message_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('api_client_id', sa.String(length=64), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('folder', sa.String(length=32), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_hash', name='uq_message_events_tenant_hash')
    )
    with op.batch_alter_table('message_events', schema=None) as batch_op:
        batch_op.create_index('ix_message_events_tenant_ts', ['tenant_id', 'timestamp'], unique=False)

    op.create_table('sender_domain_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('messages', sa.Integer(), nullable=False),
    sa.Column('convicted', sa.Integer(), nullable=False),
    sa.Column('rp_mismatch', sa.Integer(), nullable=False),
    sa.Column('reply_to_mismatch', sa.Integer(), nullable=False),
    sa.Column('convicted_reply_to_mismatch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'day', 'domain', 'direction', name='uq_sender_domain_daily')
    )
    with op.batch_alter_table('sender_domain_daily', schema=None) as batch_op:
        batch_op.create_index('ix_sender_domain_daily_lookup', ['tenant_id', 'domain'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs_cursor', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('logs_first_hour', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('logs_collected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('logs_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('logs_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logs_gaps', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('profile')
        batch_op.drop_column('logs_gaps')
        batch_op.drop_column('logs_note')
        batch_op.drop_column('logs_status')
        batch_op.drop_column('logs_collected_at')
        batch_op.drop_column('logs_first_hour')
        batch_op.drop_column('logs_cursor')

    with op.batch_alter_table('sender_domain_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_sender_domain_daily_lookup')

    op.drop_table('sender_domain_daily')
    with op.batch_alter_table('message_events', schema=None) as batch_op:
        batch_op.drop_index('ix_message_events_tenant_ts')

    op.drop_table('message_events')
    with op.batch_alter_table('log_files', schema=None) as batch_op:
        batch_op.drop_index('ix_log_files_tenant_type_date')

    op.drop_table('log_files')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_tenant_ts')

    op.drop_table('audit_events')
    op.drop_table('dns_cache')
    # ### end Alembic commands ###
